# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c8b2fb8a5f110a76a17a1556a0edd1530a11c6c1af31583855718b63405bd005d8570d07f19ba7fb8224e201eab2492ac4fc55e802052a0da9333906eedd414

test:
  secret_key_base: 9e079bc36ae1467cbb823f21d159918191dccea05bd36c17ae9b7d2dddf143a2b1c00cd8ea490d92ca865d390318036ca550a785fec9a4e8f919bd156d9c39d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
